# Generated by Django 5.1.1 on 2025-04-04 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='voter_images/')),
                ('qr_data', models.CharField(max_length=255, unique=True)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
