# Generated by Django 5.1.1 on 2025-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='qr_data',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
